/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as GarantiasIndexRouteImport } from './routes/garantias.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NewsNewsIdRouteImport } from './routes/news.$newsId'
import { Route as GarantiasGarantiaIdRouteImport } from './routes/garantias.$garantiaId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminParceirosRouteImport } from './routes/admin/parceiros'
import { Route as AdminNewsRouteImport } from './routes/admin/news'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminGovernancaRouteImport } from './routes/admin/governanca'
import { Route as AdminGarantiasRouteImport } from './routes/admin/garantias'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'
import { Route as AdminCapitalRouteImport } from './routes/admin/capital'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminBrandCardsRouteImport } from './routes/admin/brand-cards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasIndexRoute = GarantiasIndexRouteImport.update({
  id: '/garantias/',
  path: '/garantias/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasGarantiaIdRoute = GarantiasGarantiaIdRouteImport.update({
  id: '/garantias/$garantiaId',
  path: '/garantias/$garantiaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParceirosRoute = AdminParceirosRouteImport.update({
  id: '/admin/parceiros',
  path: '/admin/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/admin/navigation',
  path: '/admin/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/admin/modules',
  path: '/admin/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGovernancaRoute = AdminGovernancaRouteImport.update({
  id: '/admin/governanca',
  path: '/admin/governanca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGarantiasRoute = AdminGarantiasRouteImport.update({
  id: '/admin/garantias',
  path: '/admin/garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/admin/footer',
  path: '/admin/footer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCapitalRoute = AdminCapitalRouteImport.update({
  id: '/admin/capital',
  path: '/admin/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandCardsRoute = AdminBrandCardsRouteImport.update({
  id: '/admin/brand-cards',
  path: '/admin/brand-cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/brand-cards': typeof AdminBrandCardsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/capital': typeof AdminCapitalRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/garantias': typeof AdminGarantiasRoute
  '/admin/governanca': typeof AdminGovernancaRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/garantias/$garantiaId': typeof GarantiasGarantiaIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/garantias/': typeof GarantiasIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/brand-cards': typeof AdminBrandCardsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/capital': typeof AdminCapitalRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/garantias': typeof AdminGarantiasRoute
  '/admin/governanca': typeof AdminGovernancaRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/garantias/$garantiaId': typeof GarantiasGarantiaIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/admin': typeof AdminIndexRoute
  '/garantias': typeof GarantiasIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/brand-cards': typeof AdminBrandCardsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/capital': typeof AdminCapitalRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/garantias': typeof AdminGarantiasRoute
  '/admin/governanca': typeof AdminGovernancaRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/garantias/$garantiaId': typeof GarantiasGarantiaIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/garantias/': typeof GarantiasIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/brand-cards'
    | '/admin/branding'
    | '/admin/capital'
    | '/admin/footer'
    | '/admin/garantias'
    | '/admin/governanca'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/navigation'
    | '/admin/news'
    | '/admin/parceiros'
    | '/admin/seo'
    | '/admin/stats'
    | '/admin/users'
    | '/garantias/$garantiaId'
    | '/news/$newsId'
    | '/admin/'
    | '/garantias/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/brand-cards'
    | '/admin/branding'
    | '/admin/capital'
    | '/admin/footer'
    | '/admin/garantias'
    | '/admin/governanca'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/navigation'
    | '/admin/news'
    | '/admin/parceiros'
    | '/admin/seo'
    | '/admin/stats'
    | '/admin/users'
    | '/garantias/$garantiaId'
    | '/news/$newsId'
    | '/admin'
    | '/garantias'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/admin/brand-cards'
    | '/admin/branding'
    | '/admin/capital'
    | '/admin/footer'
    | '/admin/garantias'
    | '/admin/governanca'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/modules'
    | '/admin/navigation'
    | '/admin/news'
    | '/admin/parceiros'
    | '/admin/seo'
    | '/admin/stats'
    | '/admin/users'
    | '/garantias/$garantiaId'
    | '/news/$newsId'
    | '/admin/'
    | '/garantias/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminBrandCardsRoute: typeof AdminBrandCardsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCapitalRoute: typeof AdminCapitalRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminGarantiasRoute: typeof AdminGarantiasRoute
  AdminGovernancaRoute: typeof AdminGovernancaRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminParceirosRoute: typeof AdminParceirosRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  GarantiasGarantiaIdRoute: typeof GarantiasGarantiaIdRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  GarantiasIndexRoute: typeof GarantiasIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias/': {
      id: '/garantias/'
      path: '/garantias'
      fullPath: '/garantias/'
      preLoaderRoute: typeof GarantiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias/$garantiaId': {
      id: '/garantias/$garantiaId'
      path: '/garantias/$garantiaId'
      fullPath: '/garantias/$garantiaId'
      preLoaderRoute: typeof GarantiasGarantiaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parceiros': {
      id: '/admin/parceiros'
      path: '/admin/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AdminParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/admin/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/governanca': {
      id: '/admin/governanca'
      path: '/admin/governanca'
      fullPath: '/admin/governanca'
      preLoaderRoute: typeof AdminGovernancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/garantias': {
      id: '/admin/garantias'
      path: '/admin/garantias'
      fullPath: '/admin/garantias'
      preLoaderRoute: typeof AdminGarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/admin/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/capital': {
      id: '/admin/capital'
      path: '/admin/capital'
      fullPath: '/admin/capital'
      preLoaderRoute: typeof AdminCapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/brand-cards': {
      id: '/admin/brand-cards'
      path: '/admin/brand-cards'
      fullPath: '/admin/brand-cards'
      preLoaderRoute: typeof AdminBrandCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminBrandCardsRoute: AdminBrandCardsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCapitalRoute: AdminCapitalRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminGarantiasRoute: AdminGarantiasRoute,
  AdminGovernancaRoute: AdminGovernancaRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminParceirosRoute: AdminParceirosRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  GarantiasGarantiaIdRoute: GarantiasGarantiaIdRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  GarantiasIndexRoute: GarantiasIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
